# Generated by Django 4.0.7 on 2022-09-22 21:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('address3', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=13)),
                ('justification', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('wait', 'Awaiting approval'), ('appr', 'Approved'), ('reje', 'Rejected'), ('sent', 'Sent'), ('deli', 'Delivered')], default='wait', max_length=5)),
                ('comments', models.TextField(blank=True, max_length=500)),
                ('date_placed', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('lap', 'Laptop'), ('pho', 'Phone'), ('acc', 'accessory')], max_length=3)),
                ('release', models.DateField()),
                ('description', models.TextField(max_length=100)),
                ('roles_allowed', models.CharField(choices=[('admin', 'Administrative Staff'), ('tech', 'Technical Staff'), ('all', 'All Roles')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_type', models.CharField(choices=[('ret', 'Return'), ('req', 'Request')], max_length=4)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='cyod.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='cyod.product')),
            ],
        ),
    ]
