# Generated by Django 4.0.7 on 2022-09-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyod', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
