# Generated by Django 4.0.7 on 2022-09-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyod', '0002_order_date_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_placed',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('wait', 'Awaiting approval'), ('appr', 'Approved'), ('reje', 'Rejected'), ('sent', 'Sent'), ('deli', 'Delivered')], default='wait', max_length=5),
        ),
    ]
