# Generated by Django 4.0.7 on 2022-09-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyod', '0004_alter_order_date_placed_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_placed',
            field=models.DateField(blank=True, default=None),
        ),
    ]
