# Generated by Django 4.0.7 on 2022-09-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyod', '0005_alter_order_date_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_placed',
            field=models.DateField(default=None, null=True),
        ),
    ]
