# Generated by Django 4.0.7 on 2022-10-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyod', '0006_alter_order_date_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='town',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
