# Generated by Django 4.0.7 on 2022-09-19 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cyod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_placed',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
