# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: link check - black
        run: |
          pip install -Iv black==22.6.0
          python3 -m black . --check --config=./poetry/pyproject.toml

          
      - name: Test with django tests
        run: |
            docker-compose -f docker-compose-test.yml up

  deploy:
    
   needs: [test]
   runs-on: ubuntu-latest
   if: startsWith(github.ref, 'refs/tags/v')
   steps:
   
    - name: Checkout
      uses: actions/checkout@v2
      
    - name:  Build, Push and Release a Docker container to Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_MAIN }}
        process_type: web




   
   
   
